version: '2'
services:
  jenkins:
    restart: always
    environment:
#      - JENKINS_OPTS=--httpPort=-1 --httpsPort=8080 --httpsCertificate=/var/lib/jenkins/cert --httpsPrivateKey=/var/lib/jenkins/pk --prefix=/jenkins-ci
      - JENKINS_OPTS=--httpPort=8080 --prefix=/jenkins-ci
      - TZ=America/New_York
    image: 'jenkins/jenkins:lts'
    expose:
      - 8080
    volumes:
      # All Jenkins data lives in an external volume that is persistent.
      - 'jenkins_home:/var/jenkins_home'
      # Mount Git repo from the host to backup the configuration files under
      # version control in the Jenkins home directory
      - '${GIT_REPO}:/home/git/jenkins.git'
      # Private and public SSH keys that the Jenkins CI server will be using
      # to connect to the slave agents.
      - './secrets/jenkins_id_rsa:/var/jenkins_home/.ssh/id_rsa:ro'
      - './secrets/jenkins_id_rsa.pub:/var/jenkins_home/.ssh/id_rsa.pub:ro'
  nginx:
    restart: always
    image: 'nginx:latest'
    volumes:
      - './nginx.conf:/etc/nginx/conf.d/nginx.conf:ro'
#      - './secrets/cert.pem:/etc/nginx/ssl/server.crt:ro'
#      - './secrets/privkey.pem:/etc/nginx/ssl/server.key:ro'
      - './secrets/dhparam.pem:/etc/ssl/certs/dhparam.pem:ro'
      - 'secrets:/etc/letsencrypt:ro'
      - 'www:/var/www/html:ro'
    ports:
      - '80:80'
      - '443:443'
    links:
      - jenkins
volumes:
  jenkins_home:
    external: true 
  secrets:
    external:
      name: ${SECRETS_VOLUME}
  www:
    external:
      name: ${DATA_WWW}

