version: '2'
services:
  jenkins:
    restart: always
    environment:
#      - JENKINS_OPTS=--httpPort=-1 --httpsPort=8080 --httpsCertificate=/var/lib/jenkins/cert --httpsPrivateKey=/var/lib/jenkins/pk --prefix=/jenkins-ci
      - JENKINS_OPTS=--httpPort=8080 --prefix=/jenkins-ci
      - TZ=America/New_York
    image: 'jenkins/jenkins:lts'
    expose:
      - 8080
    ports:
      - '50000:50000'
    volumes:
      # All Jenkins data lives in an external volume that is persistent.
      - 'jenkins_home:/var/jenkins_home'
      # Mount Git repo from the host to backup the configuration files under
      # version control in the Jenkins home directory
      - '${GIT_REPO}:/home/git/jenkins.git'
      # Private and public SSH keys that the Jenkins CI server will be using
      # to connect to the slave agents.
      - './secrets/jenkins_id_rsa:/var/jenkins_home/.ssh/id_rsa:ro'
      - './secrets/jenkins_id_rsa.pub:/var/jenkins_home/.ssh/id_rsa.pub:ro'
    working_dir: /var/jenkins_home
  nginx:
    restart: always
    image: 'nginx:latest'
    volumes:
      # nginx server configuration file.
      - './nginx.conf:/etc/nginx/conf.d/nginx.conf:ro'
      # Diffie-Helman parameters for high-quality SSL config.
      - './secrets/dhparam.pem:/etc/ssl/certs/dhparam.pem:ro'
      # Persistent volume with letsencryt trusted SSL certificate.
      - 'secrets:/etc/letsencrypt:ro'
      # Mount external volume data with Jekyll site that has been deployed by 
      # Git post-receive hook.
      - 'www:/var/www/html:ro'
    ports:
      - '80:80'
      - '443:443'
    links:
      - jenkins
volumes:
  jenkins_home:
    external: true 
  secrets:
    external:
      name: ${SECRETS_VOLUME}
  www:
    external:
      name: ${DATA_WWW}

